import type { Metadata } from "next";

import "./globals.css";

import "@fontsource-variable/nunito-sans";

import "@fontsource-variable/rubik";
import "@fontsource/jomhuria";
import "@fontsource/poppins";
import AppContainer from "@/components/AppContainer";
import OnlineChat from "@/components/OnlineChat";

export const metadata: Metadata = {
  title: "SolacaTech App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <AppContainer>
          <OnlineChat />
          {children}
        </AppContainer>
      </body>
    </html>
  );
}
