import type { Metadata } from "next";

import "./globals.css";

// Supports weights 200-900
import "@fontsource-variable/nunito-sans";

// Supports weights 300-900
import "@fontsource-variable/rubik";
import "@fontsource/jomhuria";
import AppContainer from "@/components/AppContainer";

export const metadata: Metadata = {
  title: "SolacaTech App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <AppContainer>{children}</AppContainer>
      </body>
    </html>
  );
}
